### ISSUE TITLE
Find another name for this crate

### ISSUE THREAD

**Issue by killercup** [killercup/convey#9]
Find another name for this crate, or take over <https://crates.io/crates/output> (which I don't really want to do).

The name should evoke the following:

- output/print things
- flexibie
- concise
- multiple targets, compatibility without effort

**Comment by spacekookie** [comment]
`pretty.rs`

*drops mic* :wink:

**Comment by killercup** [comment]
Ah, yes, I forgot the mention that the name should also convey our hightened sense for aesthetics!

Actually, though… what about 'convey'?

**Comment by killercup** [comment]
Renamed to 'convey' in #25
